---
version: 2

project_name: fleet

env:
  - CGO_ENABLED=0
  - IS_HOTFIX={{ if isEnvSet "IS_HOTFIX"}}{{ .Env.IS_HOTFIX }}{{else}}false{{end}}

release:
  prerelease: auto
  disable: "{{ .Env.IS_HOTFIX }}"

changelog:
  disable: false
  use: github-native

before:
  hooks:
    - go mod download

archives:
  - id: fleet-controller
    formats: [ "binary" ]
    name_template: "{{ .Binary }}"
    builds:
      - fleet-controller

  - id: fleet-agent
    formats: [ "binary" ]
    name_template: "{{ .Binary }}"
    builds:
      - fleet-agent

  - id: fleet-cli
    formats: [ "binary" ]
    name_template: "{{ .Binary }}"
    builds:
      - fleet-cli

builds:
  -
    id: fleet-controller
    main: ./cmd/fleetcontroller
    binary: fleetcontroller-{{ .Os }}-{{ .Arch }}{{ if .Arm }}64{{ end }}
    no_unique_dist_dir: true
    # gcflags:
    #   - all="-N -l"
    ldflags:
      - -w -s
      - -X github.com/rancher/fleet/pkg/version.GitCommit={{ .Commit }}
      - -X github.com/rancher/fleet/pkg/version.Version={{ .Tag }}
    targets:
    - linux_s390x
  -
    id: fleet-agent
    main: ./cmd/fleetagent
    binary: fleetagent-{{ .Os }}-{{ .Arch }}{{ if .Arm }}64{{ end }}
    no_unique_dist_dir: true
    ldflags:
      - -w -s
      - -X github.com/rancher/fleet/pkg/version.GitCommit={{ .Commit }}
      - -X github.com/rancher/fleet/pkg/version.Version={{ .Tag }}
    targets:
    - linux_s390x
  -
    id: fleet-cli
    main: ./cmd/fleetcli
    binary: fleet-{{ .Os }}-{{ .Arch }}{{ if .Arm }}64{{ end }}
    no_unique_dist_dir: true
    ldflags:
      - -w -s
      - -X github.com/rancher/fleet/pkg/version.GitCommit={{ .Commit }}
      - -X github.com/rancher/fleet/pkg/version.Version={{ .Tag }}
    targets:
    - linux_s390x
  -
    id: fleet-benchmark
    main: ./benchmarks/cmd
    binary: fleet-benchmark-{{ .Os }}-{{ .Arch }}{{ if .Arm }}64{{ end }}
    no_unique_dist_dir: true
    ldflags:
      - -w -s
      - -X github.com/rancher/fleet/pkg/version.GitCommit={{ .Commit }}
      - -X github.com/rancher/fleet/pkg/version.Version={{ .Tag }}
    targets:
    - linux_s390x

snapshot:
  version_template: "{{ .Tag }}-next"

dockers:
  # TODO: skip fleet-controller s390x due to opensuse repository does not have s390x packages. Will find a replacement later.
  # fleet-controller images
  # -
  #   use: buildx
  #   id: fleet-s390x-public
  #   skip_push: "{{ .Env.IS_HOTFIX }}"
  #   goos: linux
  #   goarch: s390x
  #   ids:
  #   - fleet-controller
  #   - fleet-cli
  #   image_templates:
  #   - "ghcr.io/dnse-tech/fleet:{{ .Tag }}-linux-s390x"
  #   dockerfile: package/Dockerfile
  #   build_flag_templates:
  #   - "--pull"
  #   - "--label=org.opencontainers.image.created={{.Date}}"
  #   - "--label=org.opencontainers.image.title={{.ProjectName}}"
  #   - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  #   - "--label=org.opencontainers.image.version={{.Version}}"
  #   - "--label=org.opencontainers.image.source=https://github.com/rancher/fleet"
  #   - "--build-arg=ARCH=s390x"
  #   - "--build-arg=BUILD_ENV=goreleaser"
  #   - "--platform=linux/s390x"
  #   extra_files: [ "package/log.sh" ]
  # fleet-agent images
  -
    use: buildx
    id: fleet-agent-s390x-public
    skip_push: "{{ .Env.IS_HOTFIX }}"
    goos: linux
    goarch: s390x
    ids:
    - fleet-agent
    image_templates:
    - "ghcr.io/dnse-tech/fleet-agent:{{ .Tag }}-linux-s390x"
    dockerfile: package/Dockerfile.agent
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source=https://github.com/rancher/fleet"
    - "--build-arg=ARCH=s390x"
    - "--build-arg=BUILD_ENV=goreleaser"
    - "--platform=linux/s390x"
