---
version: 2

project_name: fleet

env:
  - CGO_ENABLED=0
  - IS_HOTFIX={{ if isEnvSet "IS_HOTFIX"}}{{ .Env.IS_HOTFIX }}{{else}}false{{end}}

release:
  prerelease: auto
  disable: "{{ .Env.IS_HOTFIX }}"

changelog:
  disable: false
  use: github-native

before:
  hooks:
    - go mod download

archives:
  - id: fleet-controller
    formats: [ "binary" ]
    name_template: "{{ .Binary }}"
    ids:
      - fleet-controller

  - id: fleet-agent
    formats: [ "binary" ]
    name_template: "{{ .Binary }}"
    ids:
      - fleet-agent

  - id: fleet-cli
    formats: [ "binary" ]
    name_template: "{{ .Binary }}"
    ids:
      - fleet-cli

  - id: fleet-benchmark
    formats: [ "binary" ]
    name_template: "{{ .Binary }}"
    ids:
      - fleet-benchmark

builds:
  - id: fleet-controller
    main: ./cmd/fleetcontroller
    binary: fleetcontroller-{{ .Os }}-{{ .Arch }}{{ if .Arm }}64{{ end }}
    no_unique_dist_dir: true
    ldflags:
      - -w -s
      - -X github.com/rancher/fleet/pkg/version.GitCommit={{ .Commit }}
      - -X github.com/rancher/fleet/pkg/version.Version={{ .Tag }}
    targets:
      - linux_amd64
      - linux_arm64
      - linux_s390x
  - id: fleet-agent
    main: ./cmd/fleetagent
    binary: fleetagent-{{ .Os }}-{{ .Arch }}{{ if .Arm }}64{{ end }}
    no_unique_dist_dir: true
    ldflags:
      - -w -s
      - -X github.com/rancher/fleet/pkg/version.GitCommit={{ .Commit }}
      - -X github.com/rancher/fleet/pkg/version.Version={{ .Tag }}
    targets:
      - linux_amd64
      - linux_arm64
      - linux_s390x
  - id: fleet-cli
    main: ./cmd/fleetcli
    binary: fleet-{{ .Os }}-{{ .Arch }}{{ if .Arm }}64{{ end }}
    no_unique_dist_dir: true
    ldflags:
      - -w -s
      - -X github.com/rancher/fleet/pkg/version.GitCommit={{ .Commit }}
      - -X github.com/rancher/fleet/pkg/version.Version={{ .Tag }}
    targets:
      - linux_amd64
      - linux_arm64
      - linux_s390x
  - id: fleet-benchmark
    main: ./benchmarks/cmd
    binary: fleet-benchmark-{{ .Os }}-{{ .Arch }}{{ if .Arm }}64{{ end }}
    no_unique_dist_dir: true
    ldflags:
      - -w -s
      - -X github.com/rancher/fleet/pkg/version.GitCommit={{ .Commit }}
      - -X github.com/rancher/fleet/pkg/version.Version={{ .Tag }}
    targets:
      - linux_amd64
      - linux_arm64
      - linux_s390x

snapshot:
  version_template: "{{ .Tag }}-next"

dockers:
  # fleet-controller amd64
  - use: buildx
    id: fleet-amd64
    skip_push: "{{ .Env.IS_HOTFIX }}"
    goos: linux
    goarch: amd64
    ids:
      - fleet-controller
      - fleet-cli
    image_templates:
      - "ghcr.io/dnse-tech/fleet:{{ .Tag }}-linux-amd64"
    dockerfile: package/Dockerfile
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/dnse-tech/fleet"
      - "--build-arg=ARCH=amd64"
      - "--build-arg=BUILD_ENV=goreleaser"
      - "--platform=linux/amd64"
    extra_files: ["package/log.sh"]
  # fleet-controller arm64
  - use: buildx
    id: fleet-arm64
    skip_push: "{{ .Env.IS_HOTFIX }}"
    goos: linux
    goarch: arm64
    ids:
      - fleet-controller
      - fleet-cli
    image_templates:
      - "ghcr.io/dnse-tech/fleet:{{ .Tag }}-linux-arm64"
    dockerfile: package/Dockerfile
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/dnse-tech/fleet"
      - "--build-arg=ARCH=arm64"
      - "--build-arg=BUILD_ENV=goreleaser"
      - "--platform=linux/arm64/v8"
    extra_files: ["package/log.sh"]
  # fleet-controller s390x
  - use: buildx
    id: fleet-s390x
    skip_push: "{{ .Env.IS_HOTFIX }}"
    goos: linux
    goarch: s390x
    ids:
      - fleet-controller
      - fleet-cli
    image_templates:
      - "ghcr.io/dnse-tech/fleet:{{ .Tag }}-linux-s390x"
    dockerfile: package/Dockerfile
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/dnse-tech/fleet"
      - "--build-arg=ARCH=s390x"
      - "--build-arg=BUILD_ENV=goreleaser"
      - "--platform=linux/s390x"
    extra_files: ["package/log.sh"]
  # fleet-agent amd64
  - use: buildx
    id: fleet-agent-amd64
    skip_push: "{{ .Env.IS_HOTFIX }}"
    goos: linux
    goarch: amd64
    ids:
      - fleet-agent
    image_templates:
      - "ghcr.io/dnse-tech/fleet-agent:{{ .Tag }}-linux-amd64"
    dockerfile: package/Dockerfile.agent
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/dnse-tech/fleet"
      - "--build-arg=ARCH=amd64"
      - "--build-arg=BUILD_ENV=goreleaser"
      - "--platform=linux/amd64"
  # fleet-agent arm64
  - use: buildx
    id: fleet-agent-arm64
    skip_push: "{{ .Env.IS_HOTFIX }}"
    goos: linux
    goarch: arm64
    ids:
      - fleet-agent
    image_templates:
      - "ghcr.io/dnse-tech/fleet-agent:{{ .Tag }}-linux-arm64"
    dockerfile: package/Dockerfile.agent
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/dnse-tech/fleet"
      - "--build-arg=ARCH=arm64"
      - "--build-arg=BUILD_ENV=goreleaser"
      - "--platform=linux/arm64/v8"
  # fleet-agent s390x
  - use: buildx
    id: fleet-agent-s390x
    skip_push: "{{ .Env.IS_HOTFIX }}"
    goos: linux
    goarch: s390x
    ids:
      - fleet-agent
    image_templates:
      - "ghcr.io/dnse-tech/fleet-agent:{{ .Tag }}-linux-s390x"
    dockerfile: package/Dockerfile.agent
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/dnse-tech/fleet"
      - "--build-arg=ARCH=s390x"
      - "--build-arg=BUILD_ENV=goreleaser"
      - "--platform=linux/s390x"

docker_manifests:
  # Multi-arch manifest for fleet controller
  - name_template: "ghcr.io/dnse-tech/fleet:{{ .Tag }}"
    id: fleet-manifest
    skip_push: "{{ .Env.IS_HOTFIX }}"
    image_templates:
      - "ghcr.io/dnse-tech/fleet:{{ .Tag }}-linux-amd64"
      - "ghcr.io/dnse-tech/fleet:{{ .Tag }}-linux-arm64"
      - "ghcr.io/dnse-tech/fleet:{{ .Tag }}-linux-s390x"
  # Multi-arch manifest for fleet agent
  - name_template: "ghcr.io/dnse-tech/fleet-agent:{{ .Tag }}"
    id: fleet-agent-manifest
    skip_push: "{{ .Env.IS_HOTFIX }}"
    image_templates:
      - "ghcr.io/dnse-tech/fleet-agent:{{ .Tag }}-linux-amd64"
      - "ghcr.io/dnse-tech/fleet-agent:{{ .Tag }}-linux-arm64"
      - "ghcr.io/dnse-tech/fleet-agent:{{ .Tag }}-linux-s390x"
